nodeLinker: node-modules

packageExtensions:
  react-virtual@*:
    peerDependencies:
      react: ^16.6.3 || ^17.0.0 || ^18.0.0 || ^19.0.0
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
  "@mdx-js/mdx@*":
    peerDependencies:
      acorn: "*"
  "@mdx-js/esbuild@*":
    peerDependencies:
      acorn: "*"
  pliny@*:
    peerDependencies:
      "@algolia/client-search": "*"
      acorn: "*"
  mdx-bundler@*:
    peerDependencies:
      acorn: "*"
  "@contentlayer2/core@*":
    peerDependencies:
      acorn: "*"
  "@contentlayer2/cli@*":
    peerDependencies:
      acorn: "*"
  "@contentlayer2/client@*":
    peerDependencies:
      acorn: "*"
  "@contentlayer2/source-files@*":
    peerDependencies:
      acorn: "*"
  "@contentlayer2/source-remote-files@*":
    peerDependencies:
      acorn: "*"
  contentlayer2@*:
    peerDependencies:
      acorn: "*"
  next-contentlayer2@*:
    peerDependencies:
      acorn: "*"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
